### PR TITLE
Enable checkaction=context in dub

### PR DESCRIPTION
**Pull request by Geod24**
This will fail with < 2.087.1

### CODE REVIEW

**Comment by Geod24** [comment]
This is blocked by a bunch of upstream fixes

**Comment by Geod24** [comment]
Would be great to get someone to look into this one at some point.

**Comment by Geod24** [comment]
This still has issues...

```
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld.bfd: /tmp/.rdmd-0/rdmd-build.d-E96E07B52D5C24B890B67CA5F414DDBA/objs/build.o: in function `_D4core8internal7dassert__T14_d_assert_failVAyaa1_3cTmTmZQBeFNaNbNiNfxmxmZQBe':
attributes.d:(.text._D4core8internal7dassert__T14_d_assert_failVAyaa1_3cTmTmZQBeFNaNbNiNfxmxmZQBe[_D4core8internal7dassert__T14_d_assert_failVAyaa1_3cTmTmZQBeFNaNbNiNfxmxmZQBe]+0x20): undefined reference to `_D4core8internal7dassert__T24miniFormatFakeAttributesTmZQBdFNaNbNiNfKxmZAya'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld.bfd: attributes.d:(.text._D4core8internal7dassert__T14_d_assert_failVAyaa1_3cTmTmZQBeFNaNbNiNfxmxmZQBe[_D4core8internal7dassert__T14_d_assert_failVAyaa1_3cTmTmZQBeFNaNbNiNfxmxmZQBe]+0x31): undefined reference to `_D4core8internal7dassert__T24miniFormatFakeAttributesTmZQBdFNaNbNiNfKxmZAya'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld.bfd: /tmp/.rdmd-0/rdmd-build.d-E96E07B52D5C24B890B67CA5F414DDBA/objs/build.o: in function `_D3std8typecons__T10RefCountedTSQBe4file15DirIteratorImplVEQCfQCe24RefCountedAutoInitializei0ZQCy6__dtorMFZv':
attributes.d:(.text._D3std8typecons__T10RefCountedTSQBe4file15DirIteratorImplVEQCfQCe24RefCountedAutoInitializei0ZQCy6__dtorMFZv[_D3std8typecons__T10RefCountedTSQBe4file15DirIteratorImplVEQCfQCe24RefCountedAutoInitializei0ZQCy6__dtorMFZv]+0xad): undefined reference to `_D4core8internal7dassert__T14_d_assert_failVAyaa1_3eTmTmZQBeFNaNbNiNfKxmxmZQBf'
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
```

**Comment by Geod24** [comment]
https://issues.dlang.org/show_bug.cgi?id=19937

**Comment by Geod24** [comment]
So it passes with DMD but not with LDC. It might be because we're using `bfd` instead of `gold` ?
LDC calls it "buggy old linker" but I wonder if the bug is really in `ld.bfd`...

**Comment by Geod24** [comment]
So we dropped DMD. And I've seen Kinke actively working on this. We might get lucky and get it to work in either LDC 1.21.0 (if we're *really* lucky), or LDC 1.22.0. Let's stay tuned for the LDC beta for once.

**Comment by AndrejMitrovic** [comment]
Can close this now? Or was the plan enabling it for non-unittest builds too?

**Comment by Geod24** [comment]
> Or was the plan enabling it for non-unittest builds too?

Not ready to open this can of worm just yet.

> Can close this now?

Indeed, done in #2038 . It only took 1896 PRs / issues and a bit less than 2 years.
